"""Testes do parser de migrações do Alembic.

As migrações usadas aqui foram derivadas do corpus real do consumidor
Alembic/PostgreSQL — 13 arquivos em `app/alembic/versions/`, cujas 8 operações
distintas dentro de
`upgrade()` o classificador tem que cobrir sem devolver nenhum `unknown`. Onde
o corpus não cobre o caso exigido pelo aceite — `op.execute()`, `alter_column`,
`rename_table`, `create_primary_key` — a migração é inventada, mas com a forma
que um arquivo autogerado pelo Alembic teria.

Nenhum arquivo do corpus é copiado para cá: a suíte de fixtures é da QQ-2161.
"""

import string
import textwrap

import pytest

from detect.alembic import (
    _EXPANDERS,
    _OPERATIONS,
    _REFINERS,
    classify_migration,
)
from detect.severity import DUPLICATE, Severity, max_severity

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

PREAMBLE = "from alembic import op\nimport sqlalchemy as sa\n"


def migration(upgrade: str, preamble: str = PREAMBLE, downgrade: str = "pass") -> str:
    """Um arquivo de versão do Alembic com `upgrade` no corpo da função."""
    return (
        f"{preamble}\n"
        "revision = 'a1b2c3'\n"
        "down_revision = 'z9y8x7'\n"
        "branch_labels = None\n"
        "depends_on = None\n"
        "\n"
        "def upgrade() -> None:\n"
        f"{textwrap.indent(textwrap.dedent(upgrade).strip(), ' ' * 4)}\n"
        "\n"
        "def downgrade() -> None:\n"
        f"{textwrap.indent(textwrap.dedent(downgrade).strip(), ' ' * 4)}\n"
    )


def severities(source: str) -> list[Severity]:
    return [finding.severity for finding in classify_migration(source)]


def only(source: str):
    """O único finding da migração — falha se houver mais de um."""
    findings = classify_migration(source)
    assert len(findings) == 1, findings
    return findings[0]


def one(upgrade: str):
    """O único finding de um corpo de `upgrade()`."""
    return only(migration(upgrade))


def severity_of(upgrade: str) -> Severity:
    return one(upgrade).severity


def placeholders(template: str) -> set[str]:
    return {field for _, field, _, _ in string.Formatter().parse(template) if field}


# ---------------------------------------------------------------------------
# Leitura do corpo de upgrade()
# ---------------------------------------------------------------------------


class TestUpgradeBody:
    def test_returns_one_finding_per_operation_in_order(self):
        source = migration(
            """
            op.add_column("docs_signature", sa.Column("external_id", sa.UUID(), nullable=True))
            op.drop_column("docs_signature", "code")
            """
        )
        assert severities(source) == [Severity.SAFE, Severity.BREAKING]

    def test_downgrade_is_ignored(self):
        # O corpus inteiro tem `drop_table` e `drop_column` no `downgrade()`.
        # Classificá-los pintaria de vermelho toda migração que sabe se desfazer.
        source = migration(
            'op.create_table("docs_list_card")',
            downgrade='op.drop_table("docs_list_card")',
        )
        assert severities(source) == [Severity.SAFE]

    def test_a_function_that_is_not_upgrade_is_ignored(self):
        source = migration(
            'op.create_table("t")',
            preamble=PREAMBLE + "\ndef helper():\n    op.drop_table('t')\n",
        )
        assert severities(source) == [Severity.SAFE]

    def test_a_docstring_in_the_body_is_not_an_operation(self):
        assert severities(migration('"""Cria a tabela."""\nop.create_table("t")')) == [
            Severity.SAFE
        ]

    def test_an_upgrade_that_only_passes_yields_no_findings(self):
        assert classify_migration(migration("pass")) == []

    def test_a_file_without_upgrade_yields_no_findings(self):
        source = "revision = 'a1'\ndown_revision = None\n"
        assert classify_migration(source) == []

    def test_the_last_upgrade_definition_wins(self):
        source = (
            "from alembic import op\n"
            "\n"
            "def upgrade():\n"
            "    op.create_table('t')\n"
            "\n"
            "def upgrade():\n"
            "    op.drop_table('t')\n"
        )
        assert severities(source) == [Severity.BREAKING]

    def test_comments_between_operations_are_not_operations(self):
        # Toda migração autogerada do corpus vem cercada de
        # `# ### commands auto generated by Alembic ###`.
        source = migration(
            """
            # ### commands auto generated by Alembic - please adjust! ###
            op.create_table("t")
            # ### end Alembic commands ###
            """
        )
        assert severities(source) == [Severity.SAFE]


# ---------------------------------------------------------------------------
# Corpo de upgrade() que o classificador não consegue ler
# ---------------------------------------------------------------------------


class TestUpgradeBodyThatCannotBeRead:
    def test_a_with_block_is_unknown(self):
        # `op.batch_alter_table` roda as operações num `batch_op` que o
        # classificador não segue. Zero findings aqui sairia como "nada a
        # reportar" para uma migração que derruba coluna.
        finding = one(
            """
            with op.batch_alter_table("docs_signature") as batch_op:
                batch_op.drop_column("code")
            """
        )
        assert finding.severity is Severity.UNKNOWN
        assert "batch_alter_table" in finding.reason

    def test_an_operation_inside_a_conditional_is_unknown(self):
        source = migration(
            """
            if DIALECT == "postgresql":
                op.drop_column("t", "c")
            """
        )
        assert severities(source) == [Severity.UNKNOWN]

    def test_an_operation_inside_a_loop_is_unknown(self):
        source = migration(
            """
            for column in COLUMNS:
                op.drop_column("t", column)
            """
        )
        assert severities(source) == [Severity.UNKNOWN]

    def test_an_operation_inside_a_try_is_unknown(self):
        source = migration(
            """
            try:
                op.drop_column("t", "c")
            except Exception:
                pass
            """
        )
        assert severities(source) == [Severity.UNKNOWN]

    def test_an_assignment_in_the_body_is_unknown(self):
        # `conn = op.get_bind()` é o começo de um DDL que o classificador não lê.
        source = migration('conn = op.get_bind()\nconn.execute("DROP TABLE t")')
        assert max_severity(severities(source)) is Severity.UNKNOWN

    def test_a_helper_call_is_unknown_and_names_the_helper(self):
        finding = one("_recria_indices()")
        assert finding.severity is Severity.UNKNOWN
        assert "`_recria_indices`" in finding.reason

    def test_an_upgrade_defined_conditionally_is_unknown(self):
        source = (
            "from alembic import op\n"
            "if LEGACY:\n"
            "    def upgrade():\n"
            "        op.drop_table('t')\n"
            "else:\n"
            "    def upgrade():\n"
            "        pass\n"
        )
        finding = only(source)
        assert finding.severity is Severity.UNKNOWN
        assert "não é definida no corpo do módulo" in finding.reason

    def test_an_upgrade_defined_inside_a_try_is_unknown(self):
        source = (
            "from alembic import op\n"
            "try:\n"
            "    def upgrade():\n"
            "        op.drop_table('t')\n"
            "except ImportError:\n"
            "    pass\n"
        )
        assert only(source).severity is Severity.UNKNOWN

    def test_a_file_that_is_not_valid_python_is_unknown(self):
        assert only("def upgrade(:\n    pass\n").severity is Severity.UNKNOWN

    def test_an_operation_after_an_unreadable_statement_is_still_classified(self):
        # Desistir do arquivo inteiro esconderia o `drop_table` que vem depois.
        source = migration(
            """
            if LEGACY:
                op.drop_column("t", "c")
            op.drop_table("t")
            """
        )
        assert severities(source) == [Severity.UNKNOWN, Severity.BREAKING]


# ---------------------------------------------------------------------------
# Quem é `op`
# ---------------------------------------------------------------------------


class TestOpAlias:
    def test_the_corpus_import_binds_op(self):
        assert severity_of('op.drop_table("t")') is Severity.BREAKING

    def test_an_aliased_import_is_followed(self):
        source = migration(
            'alembic_op.drop_table("t")',
            preamble="from alembic import op as alembic_op\n",
        )
        assert severities(source) == [Severity.BREAKING]

    def test_a_module_import_with_an_alias_is_followed(self):
        source = migration('op.drop_table("t")', preamble="import alembic.op as op\n")
        assert severities(source) == [Severity.BREAKING]

    def test_a_name_that_is_not_the_alembic_op_is_not_an_operation(self):
        # Com `op` ligado a outro nome, `op.drop_table` é uma chamada qualquer.
        source = migration(
            'op.drop_table("t")', preamble="from alembic import op as alembic_op\n"
        )
        finding = only(source)
        assert finding.severity is Severity.UNKNOWN
        assert "`drop_table`" in finding.reason

    def test_a_qualified_call_is_not_read_as_an_operation(self):
        source = migration('alembic.op.drop_table("t")', preamble="import alembic\n")
        assert severities(source) == [Severity.UNKNOWN]

    def test_an_operation_called_through_a_variable_is_unknown(self):
        assert severity_of('OPS["drop"]("t")') is Severity.UNKNOWN

    def test_an_operation_out_of_the_table_is_unknown_and_names_itself(self):
        finding = one('op.create_foreign_key("fk", "a", "b", ["a_id"], ["id"])')
        assert finding.severity is Severity.UNKNOWN
        assert "`op.create_foreign_key`" in finding.reason


# ---------------------------------------------------------------------------
# op.f() não é operação
# ---------------------------------------------------------------------------


class TestOpFIsNotAnOperation:
    def test_op_f_nested_in_create_index_yields_one_finding(self):
        # 42 ocorrências no corpus, todas como nome de índice.
        finding = one(
            'op.create_index(op.f("ix_docs_ai_feedback_rating"), "docs_ai_feedback",'
            ' ["rating"], unique=False)'
        )
        assert finding.severity is Severity.SAFE
        assert "Índice `ix_docs_ai_feedback_rating` criado em `docs_ai_feedback`." == (
            finding.reason
        )

    def test_op_f_nested_in_drop_index_yields_one_finding(self):
        finding = one(
            'op.drop_index(op.f("ix_docs_ai_feedback_rating"), table_name="docs_ai_feedback")'
        )
        assert finding.severity is Severity.CONTROLLED
        assert finding.reason.startswith(
            "Índice `ix_docs_ai_feedback_rating` removido de `docs_ai_feedback`"
        )

    def test_op_f_alone_does_not_raise_the_severity(self):
        assert severity_of('op.f("ix_t_c")') is Severity.NONE


# ---------------------------------------------------------------------------
# As severidades do aceite
# ---------------------------------------------------------------------------


class TestDestructiveOperationsAreBreaking:
    def test_drop_table(self):
        finding = one('op.drop_table("docs_list_card")')
        assert finding.severity is Severity.BREAKING
        assert "`docs_list_card`" in finding.reason

    def test_drop_column(self):
        assert severity_of('op.drop_column("docs_signature", "external_id")') is Severity.BREAKING

    def test_rename_table(self):
        assert severity_of('op.rename_table("docs_card", "docs_list_card")') is Severity.BREAKING


class TestNewUniquenessIsBreaking:
    def test_create_unique_constraint(self):
        finding = one(
            'op.create_unique_constraint("_supplier_tenant_uc", "docs_ui_feedback",'
            ' ["supplier_id", "clinic_id"])'
        )
        assert finding.severity is Severity.BREAKING
        assert DUPLICATE in finding.reason

    def test_create_primary_key(self):
        finding = one('op.create_primary_key("pk_docs_list_card", "docs_list_card", ["id"])')
        assert finding.severity is Severity.BREAKING
        assert DUPLICATE in finding.reason

    def test_a_unique_index_says_the_same_thing_as_a_unique_constraint(self):
        # O mesmo risco de gravação, criado por índice em vez de constraint. As
        # três stacks têm que dizer a mesma frase — `detect/sql.py` diz esta.
        finding = one('op.create_index("ix_uc", "t", ["a"], unique=True)')
        assert finding.severity is Severity.BREAKING
        assert DUPLICATE in finding.reason


class TestAdditiveOperationsAreSafe:
    def test_create_table(self):
        finding = one(
            'op.create_table("docs_ai_feedback",'
            ' sa.Column("id", sa.Integer(), nullable=False),'
            ' sa.PrimaryKeyConstraint("id"))'
        )
        assert finding.severity is Severity.SAFE
        assert "`docs_ai_feedback`" in finding.reason

    def test_a_unique_constraint_inside_a_new_table_does_not_break(self):
        # Tabela nova está vazia: não há linha duplicada que impeça nada.
        assert (
            severity_of(
                'op.create_table("t", sa.Column("a", sa.Integer()),'
                ' sa.UniqueConstraint("a", name="uc_t_a"))'
            )
            is Severity.SAFE
        )

    def test_create_index(self):
        assert (
            severity_of('op.create_index("ix_t_c", "t", ["c"], unique=False)') is Severity.SAFE
        )

    def test_create_index_without_the_unique_argument(self):
        assert severity_of('op.create_index("ix_t_c", "t", ["c"])') is Severity.SAFE

    def test_create_index_with_unpredictable_uniqueness_is_unknown(self):
        assert (
            severity_of('op.create_index("ix_t_c", "t", ["c"], unique=IS_UNIQUE)')
            is Severity.UNKNOWN
        )

    @pytest.mark.parametrize(
        "upgrade", ["op.create_index(*ARGS)", "op.create_index(**SPEC)"]
    )
    def test_unpacked_arguments_are_unknown(self, upgrade):
        # `unique` ausente deixa de significar `unique=False`: o `True` pode
        # estar dentro do valor que o classificador não lê, e a diferença entre
        # os dois é a diferença entre `safe` e `breaking`.
        finding = one(upgrade)
        assert finding.severity is Severity.UNKNOWN
        assert "unicidade que o classificador não consegue ler" in finding.reason

    def test_a_truthy_unique_that_is_not_the_literal_true_is_unknown(self):
        # `unique=1` não é `unique=True`. Ler o literal com `bool()` faria o
        # classificador afirmar uma unicidade que o arquivo não declara.
        assert severity_of('op.create_index("ix", "t", ["c"], unique=1)') is Severity.UNKNOWN

    def test_a_falsy_unique_that_is_not_the_literal_false_is_unknown(self):
        assert severity_of('op.create_index("ix", "t", ["c"], unique=0)') is Severity.UNKNOWN


class TestReversibleOperationsAreControlled:
    def test_drop_index(self):
        finding = one('op.drop_index("ix_t_c", table_name="t")')
        assert finding.severity is Severity.CONTROLLED
        assert "mais lenta" in finding.reason

    def test_drop_constraint(self):
        finding = one('op.drop_constraint("_supplier_tenant_uc", "t", type_="unique")')
        assert finding.severity is Severity.CONTROLLED


# ---------------------------------------------------------------------------
# add_column: a nulidade mora dentro do sa.Column
# ---------------------------------------------------------------------------


class TestAddUniqueColumn:
    """A mesma regra do `AddField` único do Django.

    Só `server_default` preenche as linhas que já existem; o `default` do
    SQLAlchemy vale para insert novo e deixa as antigas em NULL.
    """

    @pytest.mark.parametrize(
        "column",
        (
            'sa.Column("slug", sa.String(20), server_default="", nullable=False, unique=True)',
            'sa.Column("slug", sa.String(20), server_default="x", nullable=True, unique=True)',
            'sa.Column("slug", sa.String(20), nullable=False, unique=True)',
        ),
    )
    def test_is_breaking(self, column):
        finding = one(f'op.add_column("doc", {column})')
        assert finding.severity is Severity.BREAKING
        assert DUPLICATE in finding.reason

    @pytest.mark.parametrize(
        "column",
        (
            'sa.Column("slug", sa.String(20), nullable=True, unique=True)',
            'sa.Column("slug", sa.String(20), default="x", nullable=True, unique=True)',
            'sa.Column("slug", sa.String(20), server_default=None, nullable=True, unique=True)',
            'sa.Column("slug", sa.String(20), server_default="", nullable=False, unique=False)',
        ),
    )
    def test_without_a_repeated_value_keeps_the_add_column_rule(self, column):
        assert severity_of(f'op.add_column("doc", {column})') is Severity.SAFE


class TestAddColumn:
    def test_nullable_column_is_safe(self):
        assert (
            severity_of(
                'op.add_column("docs_signature", sa.Column("external_id", sa.UUID(), nullable=True))'
            )
            is Severity.SAFE
        )

    def test_not_null_with_server_default_is_safe(self):
        # A forma de `cbec11662da5_column_added_and_constraint_widened`.
        assert (
            severity_of(
                'op.add_column("docs_ui_feedback",'
                ' sa.Column("type", sa.Integer(), server_default="1", nullable=False))'
            )
            is Severity.SAFE
        )

    def test_not_null_without_default_is_controlled(self):
        finding = one(
            'op.add_column("t", sa.Column("c", sa.Integer(), nullable=False))'
        )
        assert finding.severity is Severity.CONTROLLED
        assert "NOT NULL sem default" in finding.reason

    def test_a_column_without_nullable_is_controlled(self):
        # O Alembic autogerado sempre escreve `nullable=`; a ausência é sinal de
        # que o classificador está lendo algo que não veio do autogenerate.
        assert (
            severity_of('op.add_column("t", sa.Column("c", sa.Integer()))')
            is Severity.CONTROLLED
        )

    def test_a_column_the_classifier_cannot_read_is_unknown(self):
        finding = one('op.add_column("t", COLUMN)')
        assert finding.severity is Severity.UNKNOWN
        assert "`t`" in finding.reason

    def test_unpacked_arguments_are_unknown(self):
        assert severity_of("op.add_column(*SPEC)") is Severity.UNKNOWN

    def test_unpacked_arguments_inside_the_column_are_unknown(self):
        # A nulidade e o default que este refinador lê moram no `sa.Column`, não
        # no `add_column`: é lá dentro que o keyword ausente engana.
        assert (
            severity_of('op.add_column("t", sa.Column("c", sa.Integer(), **SPEC))')
            is Severity.UNKNOWN
        )

    def test_a_truthy_nullable_that_is_not_the_literal_true_is_controlled(self):
        # `nullable=1` não é `nullable=True`; ler o literal com `bool()` daria um
        # `safe` confiante a uma coluna cuja nulidade o arquivo não declara.
        assert (
            severity_of('op.add_column("t", sa.Column("c", sa.Integer(), nullable=1))')
            is Severity.CONTROLLED
        )

    def test_the_column_name_comes_from_the_sa_column_call(self):
        finding = one(
            'op.add_column("docs_signature", sa.Column("external_id", sa.UUID(), nullable=True))'
        )
        assert finding.reason == "Coluna `external_id` adicionada em `docs_signature`."


# ---------------------------------------------------------------------------
# alter_column: sem `existing_type` não há o que comparar
# ---------------------------------------------------------------------------


class TestAlterColumn:
    def test_without_existing_type_is_unknown(self):
        finding = one('op.alter_column("t", "c", nullable=False)')
        assert finding.severity is Severity.UNKNOWN
        assert "não conhece a definição anterior" in finding.reason

    def test_a_type_change_is_breaking(self):
        finding = one(
            'op.alter_column("t", "c", type_=sa.String(length=100),'
            ' existing_type=sa.String(length=50))'
        )
        assert finding.severity is Severity.BREAKING
        assert "Tipo da coluna `c` de `t` alterado" in finding.reason

    def test_the_same_type_written_twice_is_not_a_type_change(self):
        assert (
            severity_of(
                'op.alter_column("t", "c", type_=sa.String(length=50),'
                ' existing_type=sa.String(length=50), nullable=True,'
                ' existing_nullable=False)'
            )
            is Severity.CONTROLLED
        )

    def test_becoming_not_null_is_breaking(self):
        finding = one(
            'op.alter_column("t", "c", existing_type=sa.Integer(),'
            ' nullable=False, existing_nullable=True)'
        )
        assert finding.severity is Severity.BREAKING
        assert "passou a NOT NULL" in finding.reason

    def test_becoming_nullable_is_controlled(self):
        finding = one(
            'op.alter_column("t", "c", existing_type=sa.Integer(),'
            ' nullable=True, existing_nullable=False)'
        )
        assert finding.severity is Severity.CONTROLLED
        assert "passou a aceitar NULL" in finding.reason

    def test_not_null_without_the_previous_nullability_is_unknown(self):
        finding = one(
            'op.alter_column("t", "c", existing_type=sa.Integer(), nullable=False)'
        )
        assert finding.severity is Severity.UNKNOWN
        assert "nulidade anterior" in finding.reason

    def test_a_nullability_that_did_not_change_is_not_reported_as_a_change(self):
        assert (
            severity_of(
                'op.alter_column("t", "c", existing_type=sa.Integer(),'
                ' nullable=False, existing_nullable=False,'
                ' server_default="1", existing_server_default=None)'
            )
            is Severity.CONTROLLED
        )

    def test_a_server_default_change_is_controlled(self):
        finding = one(
            'op.alter_column("t", "c", existing_type=sa.Integer(), server_default="1")'
        )
        assert finding.severity is Severity.CONTROLLED
        assert "Default da coluna `c` de `t` alterado." == finding.reason

    def test_a_rename_is_breaking_even_without_existing_type(self):
        finding = one('op.alter_column("t", "c", new_column_name="d")')
        assert finding.severity is Severity.BREAKING
        assert "Coluna `c` de `t` renomeada" in finding.reason

    def test_nothing_the_classifier_recognizes_is_unknown(self):
        finding = one('op.alter_column("t", "c", existing_type=sa.Integer())')
        assert finding.severity is Severity.UNKNOWN

    def test_the_worst_change_wins(self):
        assert (
            severity_of(
                'op.alter_column("t", "c", type_=sa.Text(), existing_type=sa.Integer(),'
                ' server_default="x")'
            )
            is Severity.BREAKING
        )

    def test_unpacked_arguments_are_unknown(self):
        finding = one("op.alter_column(**SPEC)")
        assert finding.severity is Severity.UNKNOWN
        assert "desempacotados" in finding.reason

    def test_positional_arguments_are_read_by_position(self):
        # Uma chamada só com posicionais, cuja resposta é diferente da regra crua
        # da linha: `nullable=False` (posição 2) sobre `existing_nullable=True`
        # (posição 9). Se a leitura por posição parar de funcionar, sai o
        # `unknown` da tabela em vez deste `breaking`.
        finding = one(
            'op.alter_column("t", "c", False, False, False, None, None,'
            " sa.Integer(), None, True)"
        )
        assert finding.severity is Severity.BREAKING
        assert "Coluna `c` de `t` passou a NOT NULL" in finding.reason

    @pytest.mark.parametrize(
        "upgrade",
        [
            # Os sentinelas de "não especificado" do próprio Alembic.
            'op.alter_column("t", "c", new_column_name=None, existing_type=sa.Integer())',
            'op.alter_column("t", "c", type_=None, existing_type=sa.Integer())',
            'op.alter_column("t", "c", server_default=False, existing_type=sa.Integer())',
        ],
    )
    def test_an_explicit_sentinel_is_not_read_as_a_change(self, upgrade):
        finding = one(upgrade)
        assert finding.severity is Severity.UNKNOWN, finding
        assert "não reconhece" in finding.reason

    def test_a_full_positional_call_with_sentinels_reports_only_the_type_change(self):
        # A forma que o autogenerate escreve quando só o tipo muda: `nullable`,
        # `comment`, `server_default` e `new_column_name` chegam como sentinela.
        finding = one(
            'op.alter_column("t", "c", None, False, False, None, sa.Text(), sa.Integer())'
        )
        assert finding.severity is Severity.BREAKING
        assert "Tipo da coluna `c` de `t` alterado" in finding.reason

    def test_a_new_name_the_classifier_cannot_read_is_unknown(self):
        # Mesma ilegibilidade que `unique=IS_UNIQUE`, mesma política.
        finding = one('op.alter_column("t", "c", new_column_name=NEW)')
        assert finding.severity is Severity.UNKNOWN
        assert "renomeada para um nome que o classificador não consegue ler" in finding.reason

    def test_dropping_the_default_is_still_a_change(self):
        # `server_default=None` é DROP DEFAULT; só `False` é o sentinela.
        assert (
            severity_of('op.alter_column("t", "c", existing_type=sa.Integer(),'
                        " server_default=None)")
            is Severity.CONTROLLED
        )

    def test_an_explicit_none_existing_type_is_no_prior_state(self):
        # `nullable=True` de propósito: é a entrada cuja resposta muda se
        # `existing_type=None` passar a valer como estado anterior conhecido
        # (viraria `controlled`, "passou a aceitar NULL"). Com `nullable=False`
        # o teste passaria dos dois jeitos e não afirmaria nada.
        finding = one('op.alter_column("t", "c", nullable=True, existing_type=None)')
        assert finding.severity is Severity.UNKNOWN
        assert "não conhece a definição anterior" in finding.reason


# ---------------------------------------------------------------------------
# op.execute() delega para detect/sql.py
# ---------------------------------------------------------------------------
#
# O corpus não tem nenhuma ocorrência de `op.execute` — o aceite exige a
# delegação mesmo assim, e é aqui que ela é exercitada.


class TestExecuteDelegatesToSql:
    @pytest.mark.parametrize(
        "sql, expected",
        [
            ("DROP TABLE docs_list_card", Severity.BREAKING),
            ("ALTER TABLE t DROP COLUMN c", Severity.BREAKING),
            ("CREATE INDEX ix_t_c ON t (c)", Severity.SAFE),
            ("DROP INDEX ix_t_c", Severity.CONTROLLED),
            ("COMMIT", Severity.NONE),
        ],
    )
    def test_a_literal_statement_gets_the_sql_classifier_severity(self, sql, expected):
        assert severity_of(f'op.execute("{sql}")') is expected

    def test_the_worst_statement_of_a_script_wins(self):
        assert (
            severity_of(
                'op.execute("CREATE INDEX ix ON t (c); ALTER TABLE t DROP COLUMN c;")'
            )
            is Severity.BREAKING
        )

    def test_the_finding_carries_the_sql_operation_label(self):
        assert one('op.execute("DROP TABLE t")').operation == "DROP TABLE"

    def test_a_text_wrapper_is_unwrapped(self):
        assert severity_of('op.execute(sa.text("DROP TABLE t"))') is Severity.BREAKING

    def test_a_bare_text_wrapper_is_unwrapped(self):
        assert severity_of('op.execute(text("DROP TABLE t"))') is Severity.BREAKING

    def test_an_f_string_is_unknown(self):
        finding = one('op.execute(f"DROP TABLE {table}")')
        assert finding.severity is Severity.UNKNOWN
        assert "SQL montado dinamicamente" in finding.reason

    def test_a_variable_is_unknown(self):
        assert severity_of("op.execute(SQL)") is Severity.UNKNOWN

    def test_a_concatenation_is_unknown(self):
        assert severity_of('op.execute("DROP TABLE " + table)') is Severity.UNKNOWN

    def test_a_format_call_is_unknown(self):
        assert severity_of('op.execute("DROP TABLE {}".format(table))') is Severity.UNKNOWN

    def test_unpacked_arguments_are_unknown(self):
        assert severity_of("op.execute(*ARGS)") is Severity.UNKNOWN

    def test_empty_sql_does_not_alter_the_schema(self):
        assert severity_of('op.execute("")') is Severity.NONE

    def test_a_reason_never_echoes_a_literal_value(self):
        # O defeito que a QQ-2154 encontrou em `detect/sql.py`: um INSERT com CPF
        # reproduzido na razão que vai para o Slack.
        finding = one(
            'op.execute("INSERT INTO subjects (cpf) VALUES (\'12345678900\')")'
        )
        assert "12345678900" not in finding.reason

    def test_a_text_wrapper_with_bound_parameters_is_unknown(self):
        # `.bindparams()` devolve outra coisa, e o que ela devolve não é literal.
        assert (
            severity_of(
                'op.execute(sa.text("DELETE FROM t WHERE id = :id").bindparams(id=1))'
            )
            is Severity.UNKNOWN
        )

    def test_execution_options_do_not_hide_the_sql(self):
        # `op.execute(sqltext, execution_options)`: o segundo argumento não muda
        # o DDL, e desistir por causa dele esconderia o `DROP TABLE`.
        assert (
            severity_of('op.execute("DROP TABLE t", {"isolation_level": "AUTOCOMMIT"})')
            is Severity.BREAKING
        )


# ---------------------------------------------------------------------------
# As formas do corpus classificam sem nenhum unknown
# ---------------------------------------------------------------------------


CORPUS_SHAPES = [
    # f0f3421e338e_create_table_with_constraints / ddcbad06c156_create_table_and_index
    """
    op.create_table(
        "docs_ai_feedback",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column(
            "time_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id", "supplier_id", name="_supplier_rating_uc"),
    )
    op.create_index(
        op.f("ix_docs_ai_feedback_rating"), "docs_ai_feedback", ["rating"], unique=False
    )
    """,
    # 4f689a72a402_add_nullable_column
    'op.add_column("docs_signature", sa.Column("external_id", sa.UUID(), nullable=True))',
    # 1dc9e37bdc87_add_two_columns
    """
    op.add_column(
        "docs_signature",
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column("docs_signature", sa.Column("deleted", sa.Boolean(), nullable=True))
    """,
    # fe887fb947f0_unique_constraint_on_two_columns
    """
    op.create_unique_constraint(
        "_supplier_tenant_uc", "docs_ui_feedback", ["supplier_id", "clinic_id"]
    )
    """,
    # cbec11662da5_column_added_and_constraint_widened
    """
    op.add_column(
        "docs_ui_feedback",
        sa.Column("type", sa.Integer(), server_default="1", nullable=False),
    )
    op.drop_constraint("_supplier_tenant_uc", "docs_ui_feedback", type_="unique")
    op.create_unique_constraint(
        "_supplier_tenant_uc",
        "docs_ui_feedback",
        ["supplier_id", "clinic_id", "type"],
    )
    op.create_index(
        op.f("ix_docs_ui_feedback_type"),
        "docs_ui_feedback",
        ["type"],
        unique=False,
    )
    """,
]


class TestCorpusShapes:
    @pytest.mark.parametrize("upgrade", CORPUS_SHAPES, ids=range(len(CORPUS_SHAPES)))
    def test_no_corpus_shape_produces_an_unknown(self, upgrade):
        findings = classify_migration(migration(upgrade))
        assert findings
        assert [f for f in findings if f.severity is Severity.UNKNOWN] == []

    def test_the_unique_constraint_migration_is_the_breaking_one(self):
        source = migration(CORPUS_SHAPES[3])
        assert max_severity(severities(source)) is Severity.BREAKING


# ---------------------------------------------------------------------------
# A tabela de regras
# ---------------------------------------------------------------------------

# As 8 operações que aparecem dentro de `upgrade()` no corpus do consumidor
# Alembic, mais as que o aceite exige e o corpus não exercita.
CORPUS_OPERATIONS = [
    "add_column",
    "create_index",
    "create_table",
    "create_unique_constraint",
    "drop_column",
    "drop_constraint",
    "drop_index",
    "drop_table",
    "f",
]

REQUIRED_BY_THE_SPEC = ["alter_column", "create_primary_key", "execute", "rename_table"]

# Os parâmetros que cada refinador e cada expansor lê. Parâmetro fora da
# `signature` da linha só é achado por keyword: passado por posição, sumiria em
# silêncio e a severidade sairia pela regra crua sem ninguém ver.
PARAMETERS_READ_BY_HAND = {
    "add_column": ("column",),
    "create_index": ("unique",),
    "alter_column": (
        "nullable",
        "server_default",
        "new_column_name",
        "type_",
        "existing_type",
        "existing_nullable",
    ),
    "execute": ("sqltext",),
}


class TestRuleTableCoverage:
    @pytest.mark.parametrize("name", CORPUS_OPERATIONS + REQUIRED_BY_THE_SPEC)
    def test_every_operation_the_spec_names_has_a_rule(self, name):
        assert name in _OPERATIONS

    def test_every_refiner_belongs_to_an_operation(self):
        # Refinador sob chave digitada errada é código morto silencioso: a
        # operação continua classificando, só que sempre pela regra crua.
        assert set(_REFINERS) <= set(_OPERATIONS)

    def test_every_expander_belongs_to_an_operation(self):
        assert set(_EXPANDERS) <= set(_OPERATIONS)

    def test_no_operation_has_both_a_refiner_and_an_expander(self):
        # O expansor tem prioridade; um refinador na mesma chave nunca rodaria.
        assert not set(_REFINERS) & set(_EXPANDERS)

    @pytest.mark.parametrize("name", sorted(_OPERATIONS))
    def test_every_reason_only_cites_names_the_rule_knows_how_to_find(self, name):
        operation = _OPERATIONS[name]
        cited = placeholders(operation.reason)
        assert cited <= {"table", "target"}, name
        if "table" in cited:
            assert operation.table, name
        if "target" in cited:
            assert operation.target, name

    @pytest.mark.parametrize("name", sorted(_OPERATIONS))
    def test_the_parameters_the_rule_reads_are_in_the_signature(self, name):
        operation = _OPERATIONS[name]
        for parameter in (operation.table, operation.target):
            if parameter:
                assert parameter in operation.signature, (name, parameter)

    @pytest.mark.parametrize("name", sorted(PARAMETERS_READ_BY_HAND))
    def test_the_parameters_read_by_hand_are_in_the_signature(self, name):
        signature = _OPERATIONS[name].signature
        for parameter in PARAMETERS_READ_BY_HAND[name]:
            assert parameter in signature, (name, parameter)

    def test_every_refiner_and_expander_declares_the_parameters_it_reads(self):
        # Refinador novo sem entrada aqui entra sem ninguém conferir a
        # assinatura da linha que ele lê.
        assert set(PARAMETERS_READ_BY_HAND) == set(_REFINERS) | set(_EXPANDERS)


# ---------------------------------------------------------------------------
# Cada nome no seu lugar dentro da frase
# ---------------------------------------------------------------------------
#
# `"t" in reason` e `"c" in reason` passam os dois com a frase transposta —
# "Coluna `t` removida de `c`". Só o fragmento renderizado vê a ordem, então
# cada linha que declara `table` e `target` traz aqui a frase que ela tem que
# produzir, escrita à mão. Nomes que não são substring um do outro, senão o
# assert volta a passar por acidente.

TWO_NAMED_SENTENCES = {
    "add_column": (
        'op.add_column("paciente", sa.Column("apelido", sa.String(), nullable=True))',
        "Coluna `apelido` adicionada em `paciente`.",
    ),
    "drop_column": (
        'op.drop_column("paciente", "apelido")',
        "Coluna `apelido` removida de `paciente`",
    ),
    "alter_column": (
        'op.alter_column("paciente", "apelido", nullable=True)',
        "Coluna `apelido` de `paciente` alterada",
    ),
    "create_index": (
        'op.create_index("indice_apelido", "paciente", ["apelido"])',
        "Índice `indice_apelido` criado em `paciente`.",
    ),
    "drop_index": (
        'op.drop_index("indice_apelido", table_name="paciente")',
        "Índice `indice_apelido` removido de `paciente`",
    ),
    "create_unique_constraint": (
        'op.create_unique_constraint("restricao_apelido", "paciente", ["apelido"])',
        "Constraint UNIQUE `restricao_apelido` adicionada em `paciente`",
    ),
    "create_primary_key": (
        'op.create_primary_key("chave_apelido", "paciente", ["apelido"])',
        "Chave primária `chave_apelido` criada em `paciente`",
    ),
    "drop_constraint": (
        'op.drop_constraint("restricao_apelido", "paciente", type_="unique")',
        "Constraint `restricao_apelido` removida de `paciente`",
    ),
}


# As linhas que citam um nome só. Juntas com as de cima, cobrem toda a tabela
# menos o expansor — `test_every_row_that_labels_itself_has_a_source` é quem
# cobra isso.
ONE_NAMED_SOURCES = {
    "create_table": 'op.create_table("paciente", sa.Column("id", sa.Integer()))',
    "drop_table": 'op.drop_table("paciente")',
    "rename_table": 'op.rename_table("paciente", "pessoa")',
    "f": 'op.f("indice_apelido")',
}

LABELLED_SOURCES = {
    **{name: source for name, (source, _) in TWO_NAMED_SENTENCES.items()},
    **ONE_NAMED_SOURCES,
}


class TestEachNameLandsInItsOwnSlot:
    @pytest.mark.parametrize("name", sorted(TWO_NAMED_SENTENCES))
    def test_the_rendered_sentence_is_the_one_the_row_promises(self, name):
        operation, expected = TWO_NAMED_SENTENCES[name]
        assert expected in one(operation).reason

    def test_every_row_with_two_names_is_covered(self):
        # Linha nova com `table` e `target` entra sem frase escrita à mão e a
        # transposição volta a ser invisível.
        two_named = {
            name
            for name, operation in _OPERATIONS.items()
            if operation.table and operation.target
        }
        assert two_named == set(TWO_NAMED_SENTENCES)


# ---------------------------------------------------------------------------
# Forma do Finding
# ---------------------------------------------------------------------------

# Uma fonte por operação da tabela, mais um caso por saída de refinador e por
# fallback de expansor. `test_every_operation_in_the_table_has_a_shape_case` é
# o que impede a lista de ficar para trás quando a tabela cresce.

EVERY_KIND_OF_MIGRATION = [
    migration('op.create_table("t", sa.Column("id", sa.Integer()))'),
    migration('op.drop_table("t")'),
    migration('op.rename_table("t", "u")'),
    # add_column: as três saídas do refinador
    migration('op.add_column("t", sa.Column("c", sa.Integer(), nullable=True))'),
    migration('op.add_column("t", sa.Column("c", sa.Integer(), nullable=False))'),
    migration('op.add_column("t", COLUMN)'),
    migration('op.drop_column("t", "c")'),
    # alter_column: as saídas do refinador
    migration('op.alter_column("t", "c", nullable=False)'),
    migration('op.alter_column("t", "c", new_column_name="d")'),
    migration('op.alter_column("t", "c", type_=sa.Text(), existing_type=sa.Integer())'),
    migration(
        'op.alter_column("t", "c", existing_type=sa.Integer(), nullable=False,'
        ' existing_nullable=True)'
    ),
    migration(
        'op.alter_column("t", "c", existing_type=sa.Integer(), nullable=True,'
        ' existing_nullable=False)'
    ),
    migration('op.alter_column("t", "c", existing_type=sa.Integer(), nullable=False)'),
    migration('op.alter_column("t", "c", existing_type=sa.Integer(), server_default="1")'),
    migration('op.alter_column("t", "c", existing_type=sa.Integer())'),
    migration("op.alter_column(**SPEC)"),
    migration('op.alter_column("t", "c", new_column_name=NEW)'),
    migration('op.add_column("t", sa.Column("c", sa.Integer(), **SPEC))'),
    # create_index: as três saídas do refinador
    migration('op.create_index("ix", "t", ["c"], unique=False)'),
    migration('op.create_index("ix", "t", ["c"], unique=True)'),
    migration('op.create_index("ix", "t", ["c"], unique=IS_UNIQUE)'),
    migration("op.create_index(**SPEC)"),
    migration('op.drop_index("ix", table_name="t")'),
    migration('op.create_unique_constraint("uc", "t", ["c"])'),
    migration('op.create_primary_key("pk", "t", ["id"])'),
    migration('op.drop_constraint("uc", "t", type_="unique")'),
    # execute: as três saídas do expansor
    migration('op.execute("DROP TABLE t")'),
    migration('op.execute("")'),
    migration("op.execute(SQL)"),
    migration('op.f("ix")'),
    # o que o classificador não lê
    migration('op.create_foreign_key("fk", "a", "b", ["a_id"], ["id"])'),
    migration("with op.batch_alter_table('t') as batch_op:\n    batch_op.drop_column('c')"),
    migration("if LEGACY:\n    op.drop_table('t')"),
    migration("conn = op.get_bind()"),
    migration("_helper()"),
    migration('OPS["drop"]("t")'),
    "if LEGACY:\n    def upgrade():\n        pass\n",
    "def upgrade(:\n    pass\n",
]


class TestFindingShape:
    @pytest.mark.parametrize("name", sorted(_OPERATIONS))
    def test_every_reason_template_in_the_table_is_a_sentence(self, name):
        # A invariante direto na tabela, sem depender de alguém lembrar de
        # escrever uma fonte que exercite a linha.
        reason = _OPERATIONS[name].reason
        assert reason[0].isupper(), (name, reason)
        assert reason.endswith("."), (name, reason)

    def test_every_operation_in_the_table_has_a_shape_case(self):
        for name in _OPERATIONS:
            assert any(f"op.{name}(" in source for source in EVERY_KIND_OF_MIGRATION), name

    @pytest.mark.parametrize("source", EVERY_KIND_OF_MIGRATION)
    def test_every_finding_has_an_operation_and_a_reason(self, source):
        findings = classify_migration(source)
        assert findings, source
        for finding in findings:
            assert finding.operation, source
            assert finding.reason, source

    @pytest.mark.parametrize("source", EVERY_KIND_OF_MIGRATION)
    def test_every_reason_is_a_portuguese_sentence(self, source):
        # Pega também as razões que saem dos refinadores e dos expansores, que
        # não estão na tabela.
        for finding in classify_migration(source):
            assert finding.reason[0].isupper(), finding.reason
            assert finding.reason.endswith("."), finding.reason

    @pytest.mark.parametrize("source", EVERY_KIND_OF_MIGRATION)
    def test_no_reason_leaks_an_ast_node_type(self, source):
        # `(`Lambda`)`, `(`Starred`)`: vocabulário do parser, não do time de dados.
        for finding in classify_migration(source):
            for node_type in ("Lambda", "IfExp", "Starred", "Subscript", "Call", "Name"):
                assert f"`{node_type}`" not in finding.reason, finding.reason

    @pytest.mark.parametrize("source", EVERY_KIND_OF_MIGRATION)
    def test_no_finding_carries_a_path_or_a_line_number(self, source):
        # `Finding` descreve uma operação, não um arquivo — juntar com o caminho
        # é trabalho da QQ-2158.
        for finding in classify_migration(source):
            assert not hasattr(finding, "path")
            assert not hasattr(finding, "line")

    @pytest.mark.parametrize("name", sorted(LABELLED_SOURCES))
    def test_the_operation_label_names_the_alembic_call(self, name):
        assert one(LABELLED_SOURCES[name]).operation == f"op.{name}"

    def test_every_row_that_labels_itself_has_a_source(self):
        # Sem esta invariante, uma linha nova entra sem fonte e o teste acima
        # simplesmente não roda para ela — que foi o que aconteceu com as cinco
        # linhas de um nome só.
        assert set(_OPERATIONS) - set(LABELLED_SOURCES) == set(_EXPANDERS), (
            "linha sem fonte de rótulo; só o expansor pode ficar de fora, "
            "porque ele devolve o rótulo do statement SQL classificado"
        )


class TestReasonsNeverLeakLiterals:
    @pytest.mark.parametrize(
        "upgrade",
        [
            'op.execute("INSERT INTO subjects (cpf) VALUES (\'12345678900\')")',
            'op.add_column("subjects", sa.Column("cpf", sa.String(),'
            ' server_default="12345678900", nullable=False))',
            'op.alter_column("subjects", "cpf", existing_type=sa.String(),'
            ' server_default="12345678900")',
        ],
    )
    def test_no_reason_echoes_a_value_from_the_migration(self, upgrade):
        for finding in classify_migration(migration(upgrade)):
            assert "12345678900" not in finding.reason, finding.reason
