name: Security Workflow

on:
  workflow_call:
    secrets:
      SONAR_FOUNDATION_TOKEN:
        required: true
  workflow_dispatch:

jobs:
  static-application-security-testing:
    runs-on: runner-security-${{ github.repository_owner }}
    env:
      SONAR_HOST_URL: http://sonar.afya.tools:9000/
      APPLICATION_NAME: ${{ github.event.repository.name }}
      COMPANY: ${{ github.repository_owner }}
    steps:
      - uses: actions/checkout@master
      - name: SonarQube Scan
        run: sonar-scanner
          -Dsonar.dependencyCheck.securityHotspot=true
          -Dsonar.dependencyCheck.summarize=true
          -Dsonar.qualitygate.wait=true
          -Dsonar.projectKey=$COMPANY-$APPLICATION_NAME
          -Dsonar.projectName=$COMPANY-$APPLICATION_NAME
          -Dsonar.plugins.downloadOnlyRequired=true
          -Dsonar.token=${{ secrets.SONAR_FOUNDATION_TOKEN }}
          -Dsonar.projectBaseDir=${{ github.workspace }}
          -Dsonar.sources=.
          -Dsonar.scm.provider=git