name: 'Jira Issue Required'
author: 'José Luis da Cruz Junior'
description: 'Action para garantir que o merge só seja permitido quando a branch do PR estiver associada a um card do Jira.'

on:
  inputs:
      main-branch-name:
        required: true
        type: string
  push:
    branches: [ ${{ inputs.main-branch-name }} ]
  pull_request:
    branches: [ ${{ inputs.main-branch-name }} ]

runs:
  using: composite
  steps:
    - name: Jira Login
      uses: atlassian/gajira-login@v3
      env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Find Issue Key
        uses: atlassian/gajira-find-issue-key@v3
        with:
          string: ${{ github.head_ref }}
