name: 'Jira Issue Required'
author: 'José Luis da Cruz Junior'
description: 'Action para garantir que o merge só seja permitido quando a branch do PR estiver associada a um card do Jira.'

inputs:
    jira_base_url:
        required: true
        description: https://<your_org>.atlassian.net
    jira_user_email:
        required: true
        description: your_user@your_domain.com
    jira_api_token:
        required: true
        description: Create one at https://id.atlassian.com/manage-profile/security/api-tokens
    possible_issue_reference:
        description: Uma string que possivelmente contém o issue no Jira. Pode ser o nome da branch, o título do PR, etc. O padrão é o nome da branch.
        default: ${{ github.ref_name }}

runs:
    using: composite
    steps:
        - name: Jira Login
          uses: atlassian/gajira-login@v3
          env:
              JIRA_BASE_URL: ${{ inputs.jira_base_url }}
              JIRA_USER_EMAIL: ${{ inputs.jira_user_email }}
              JIRA_API_TOKEN: ${{ inputs.jira_api_token }}

        - name: Find Issue Key
          uses: atlassian/gajira-find-issue-key@v3
          with:
              string: ${{ inputs.possible_issue_reference }}
