name: 'Jira Issue Required'
author: 'José Luis da Cruz Junior'
description: 'Action para garantir que o merge só seja permitido quando a branch do PR estiver associada a um card do Jira.'

inputs:
  jira_base_url:
    required: true
    description: https://<your_org>.atlassian.net
  jira_user_email:
    required: true
    description: your_user@your_domain.com
  jira_api_token:
    required: true
    description: Create one at https://id.atlassian.com/manage-profile/security/api-tokens
  jira_alternative_base_url:
    required: false
    description: https://<your_org>.atlassian.net
  jira_alternative_user_email:
    required: false
    description: your_user@your_domain.com
  jira_alternative_api_token:
    required: false
    description: Create one at https://id.atlassian.com/manage-profile/security/api-tokens
  possible_issue_reference:
    description: Uma string que possivelmente contém o issue no Jira. Pode ser o nome da branch, o título do PR, etc. O padrão é o nome da branch.
    default: ""
  jira_status_allowed_to_merge:
    required: true
    description: O status do Jira que permite o merge -> To Deployment
  default_hotfix_prefix:
    required: false
    description: Prefixo da branch de hotfix. Default -> hotfix/

runs:
  using: composite
  steps:
    - name: Setup | Environment
      shell: bash
      run: |
        echo "POSSIBLE_ISSUE_REFERENCE=${{ inputs.possible_issue_reference }}" >> "$GITHUB_ENV"
        echo "ISSUE_KEY_FOUND=0" >> "$GITHUB_ENV"
        echo "HOTFIX_PREFIX_FOUND=0" >> "$GITHUB_ENV"

    - name: Get Possible Issue Reference - Default / Push Event in PR
      if: env.POSSIBLE_ISSUE_REFERENCE == '' && github.event_name == 'push' && github.event.pull_request != null
      shell: bash
      run: echo "POSSIBLE_ISSUE_REFERENCE=${{ github.ref_name }} ${{ github.event.pull_request.title }}" >> "$GITHUB_ENV"

    - name: Get Possible Issue Reference - Default / Push Event without PR
      if: env.POSSIBLE_ISSUE_REFERENCE == '' && github.event_name == 'push'
      shell: bash
      run: echo "POSSIBLE_ISSUE_REFERENCE=${{ github.ref_name }}" >> "$GITHUB_ENV"

    - name: Get Possible Issue Reference - Default / Pull Request Event
      if: env.POSSIBLE_ISSUE_REFERENCE == '' && startsWith(github.event_name, 'pull_request')
      shell: bash
      run: echo "POSSIBLE_ISSUE_REFERENCE=${{ github.head_ref }} ${{ github.event.pull_request.title }}" >> "$GITHUB_ENV"

    - name: Check if issue key exists
      env:
        JIRA_BASE_URL: ${{ inputs.jira_base_url }}
        JIRA_USER_EMAIL: ${{ inputs.jira_user_email }}
        JIRA_API_TOKEN: ${{ inputs.jira_api_token }}
        JIRA_STATUS_ALLOWED_TO_MERGE: ${{ inputs.JIRA_STATUS_ALLOWED_TO_MERGE }}
        DEFAULT_HOTFIX_PREFIX: ${{ inputs.default_hotfix_prefix }}
      shell: bash
      run: |
        ISSUE_KEY=$(echo "$POSSIBLE_ISSUE_REFERENCE" | grep -oE '[A-Z0-9]{1,10}-[0-9]+')
        echo "ISSUE_KEY=$ISSUE_KEY" >> "$GITHUB_ENV"
        echo "Searching for Jira issue $ISSUE_KEY at $JIRA_BASE_URL"
        JIRA_API_ISSUE_ENDPOINT="${JIRA_BASE_URL}/rest/api/2/issue/${ISSUE_KEY}?fields=key,status"
        echo "Requesting issue at $JIRA_API_ISSUE_ENDPOINT"

        echo "DEFAULT_HOTFIX_PREFIX [$DEFAULT_HOTFIX_PREFIX]"
        echo "Branch name ${{ github.head_ref }}"
        HOTFIX_PREFIX=$(cut -c 1-${#DEFAULT_HOTFIX_PREFIX} <<< "${{ github.head_ref }}")
        echo "HOTFIX_PREFIX [$HOTFIX_PREFIX]"

        if [ "$HOTFIX_PREFIX" == "$DEFAULT_HOTFIX_PREFIX" ]; then
          echo "HOTFIX_PREFIX_FOUND=1" >> "$GITHUB_ENV"
          echo "Hotfix branch detected, skipping Jira issue status check."
          exit 0
        fi

        JIRA_RESPONSE_STATUS=$(curl --request GET --url "${JIRA_API_ISSUE_ENDPOINT}" --user "${JIRA_USER_EMAIL}:${JIRA_API_TOKEN}" | jq .fields.status.name)
        echo "Response Status [$JIRA_RESPONSE_STATUS]"
        echo "JIRA_STATUS_ALLOWED_TO_MERGE -> [$JIRA_STATUS_ALLOWED_TO_MERGE]"
        echo "JIRA_RESPONSE_STATUS=$JIRA_RESPONSE_STATUS" >> "$GITHUB_ENV"
        echo "JIRA_STATUS_ALLOWED_TO_MERGE=$JIRA_STATUS_ALLOWED_TO_MERGE" >> "$GITHUB_ENV"

        if [ "$JIRA_RESPONSE_STATUS" != "null" ]; then
          echo "ISSUE_KEY_FOUND=1" >> "$GITHUB_ENV"
          echo "Issue key found!"
        fi

    - name: Check if issue key exists in alternative Jira
      if: env.ISSUE_KEY_FOUND == 0 && inputs.jira_alternative_base_url != '' && inputs.jira_alternative_user_email != '' && inputs.jira_alternative_api_token != ''
      env:
        JIRA_BASE_URL: ${{ inputs.jira_alternative_base_url }}
        JIRA_USER_EMAIL: ${{ inputs.jira_alternative_user_email }}
        JIRA_API_TOKEN: ${{ inputs.jira_alternative_api_token }}
        JIRA_STATUS_ALLOWED_TO_MERGE: ${{ inputs.JIRA_STATUS_ALLOWED_TO_MERGE }}
        DEFAULT_HOTFIX_PREFIX: ${{ inputs.default_hotfix_prefix }}
      shell: bash
      run: |
        ISSUE_KEY=$(echo "$POSSIBLE_ISSUE_REFERENCE" | grep -oE '[A-Z0-9]{1,10}-[0-9]+')
        echo "ISSUE_KEY=$ISSUE_KEY" >> "$GITHUB_ENV"
        echo "Alternative Jira check"
        echo "Searching for Jira issue $ISSUE_KEY at $JIRA_BASE_URL"
        JIRA_API_ISSUE_ENDPOINT="${JIRA_BASE_URL}/rest/api/2/issue/$ISSUE_KEY?fields=key,status"
        echo "Requesting issue at $JIRA_API_ISSUE_ENDPOINT"

        echo "DEFAULT_HOTFIX_PREFIX [$DEFAULT_HOTFIX_PREFIX]"
        echo "Branch name ${{ github.head_ref }}"
        HOTFIX_PREFIX=$(cut -c 1-${#DEFAULT_HOTFIX_PREFIX} <<< "${{ github.head_ref }}")
        echo "HOTFIX_PREFIX [$HOTFIX_PREFIX]"

        echo "Length of JIRA_BASE_URL: ${#JIRA_BASE_URL}"
        echo "Length of JIRA_API_ISSUE_ENDPOINT: ${#JIRA_API_ISSUE_ENDPOINT}"

        if [ "$HOTFIX_PREFIX" == "$DEFAULT_HOTFIX_PREFIX" ]; then
          echo "HOTFIX_PREFIX_FOUND=1" >> "$GITHUB_ENV"
          echo "Hotfix branch detected, skipping Jira issue status check."
          exit 0
        fi

        echo "Length of JIRA_BASE_URL: ${#JIRA_BASE_URL}"
        echo "Length of JIRA_API_ISSUE_ENDPOINT: ${#JIRA_API_ISSUE_ENDPOINT}"

        JIRA_RESPONSE_STATUS=$(curl --request GET --url "${JIRA_API_ISSUE_ENDPOINT}" --user "${JIRA_USER_EMAIL}:${JIRA_API_TOKEN}" | jq .fields.status.name)
        echo "Response Status [$JIRA_RESPONSE_STATUS]"
        echo "JIRA_STATUS_ALLOWED_TO_MERGE -> [$JIRA_STATUS_ALLOWED_TO_MERGE]"
        echo "JIRA_RESPONSE_STATUS=$JIRA_RESPONSE_STATUS" >> "$GITHUB_ENV"
        echo "JIRA_STATUS_ALLOWED_TO_MERGE=$JIRA_STATUS_ALLOWED_TO_MERGE" >> "$GITHUB_ENV"

        if [ "$JIRA_RESPONSE_STATUS" != "null" ]; then
          echo "ISSUE_KEY_FOUND=1" >> "$GITHUB_ENV"
          echo "Issue key found!"
        fi

    - name: Fail if not found
      if: env.ISSUE_KEY_FOUND == 0 && env.HOTFIX_PREFIX_FOUND == 0
      shell: bash
      run: |
        echo "Issue not found in '${{ env.POSSIBLE_ISSUE_REFERENCE }}'!"
        exit 1

    - name: Fail if status is not allowed to deploy
      if: env.ISSUE_KEY_FOUND == 1 && env.HOTFIX_PREFIX_FOUND == 0
      shell: bash
      run: |
        JIRA_STATUS_ALLOWED_TO_MERGE_STR="${{ env.JIRA_STATUS_ALLOWED_TO_MERGE }}"
        if [ ${{ env.JIRA_RESPONSE_STATUS }} != "$JIRA_STATUS_ALLOWED_TO_MERGE_STR" ]; then
          echo "Issue status is not allowed to merge because ${{ env.JIRA_RESPONSE_STATUS }} is not $JIRA_STATUS_ALLOWED_TO_MERGE_STR!"
          exit 1
        fi
