on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - converted_to_draft

jobs:
  add_waiting_review_label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Automations Repository
        uses: actions/checkout@v4

      - name: Mark PR as ready by adding/removing 'waiting review' label
        uses: ./declarative-labeler
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          when_pr_is: ready
          then_add_labels: waiting review
          also_reverse: true
