on:
  push:
    branches: [staging, main]
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:
  Security:
    runs-on: runner-security-${{ github.repository_owner }}
    steps:
      - name: Checkout Automations Repository
        uses: actions/checkout@v4

      - name: Run SonarQube
        uses: ./security
        with:
          sonar_token: ${{ secrets.SONAR_FOUNDATION_TOKEN }}
